version: '3.4'

services:
  mobileStatisticsApp:
    image: mobileStatisticsApp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
