

version: "3.8"

services:
  database:
    container_name: postgresql
    image: postgres
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - "5439:5432"
  api:
    container_name: mobilestatisticsapp.api
    restart: unless-stopped
    build:
      context: server
    ports:
      - 6578:8222
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8800
    depends_on:
      - database
  web:
    container_name: web
    restart: unless-stopped
    build:
     context: client
    ports:
      - '8080:80'
    depends_on:
      - api